Use Clapper sink if installed
jeffshee/gnome-ext-hanabi pull request #19
Opened 2022-09-14 12:15 UTC by Rafostar

When `clappersink` is installed use it for improved performance. Clapper sink also efficiently handles all kinds of subtitles (including animated karaoke) for additional benefit. When unavailable, try to fallback to `gtk4paintablesink` from gstreamer-rs plugins as 2nd best choice. Finally fallback to stock GTK media playback implementation (old code path).

**Opening as a draft, cause I did not have time yet to test it properly (only tested from command line).**

---

TO TEST:
1. Make sure `clappersink` is available (check with `gst-inspect-1.0 clappersink`).
2. Run renderer.js from this repo with `./renderer.js --windowed 640:480 --nohide -F /path/to/media.mp4`
3. Name of the used sink is included in window title (should say `clappersink`).

**Intel/AMD Wayland users** can additionally benefit from using new VA plugin (not enabled by default) that uses DMABuf sharing with the sink. To do so, try running above with `GST_PLUGIN_FEATURE_RANK=vah264dec:300,vavp9dec:300` env.

@jeffshee 
It is possible to enable and use VA plugin from within the code (not part of this MR). Since VA is new and still considered experimental I did not do it here. Let me know if you want me to go with it, and I can do another MR that enables it. For now can be tested from terminal as I written above.

Fixes #18

2022-09-14 16:59 UTC, Rafostar commented
For now, I just tested this from terminal on a VERY shitty Intel Celeron system (Atom cores). With Wayland session + VA enabled via env.

Trying to play 1080p60 video I get:
* GtkMediaStream: ~5fps, 100% CPU usage, thousands of lost frames
* Clapper sink available: 60fps, 15% CPU usage, no frames lost 😎

So far, so good. I still need to test it as actual wallpaper through. But if anybody tries before me, feedback is welcome.

2022-09-17 08:25 UTC, jeffshee commented
@Rafostar Wow thanks! I will test your codes tonight, and get back to you asap! 🤩

2022-09-17 18:43 UTC, jeffshee requested changes
Minor issue. We just need to revert the changes of the `codePath`, everything else is fine! =)

2022-09-17 18:43 UTC, jeffshee commented on src/renderer.js
>  let windowConfig = { width: 1920, height: 1080 }
```suggestion
let windowConfig = { width: 1920, height: 1080 }
let codePath = "";
```

2022-09-17 18:43 UTC, jeffshee commented on src/renderer.js
>                  case '--windowed':
```suggestion
                case '--windowed':
                case '-P':
                case '--codepath':
```

2022-09-17 18:43 UTC, jeffshee commented on src/renderer.js
>                  break;
```suggestion
                break;
            case '-P':
            case '--codepath':
                codePath = arg;
                debug(`codepath = ${codePath}`);
                break;
```

2022-09-17 18:43 UTC, jeffshee commented on src/renderer.js
> +const codePath = GLib.get_current_dir();
```suggestion
```

2022-09-17 19:02 UTC, jeffshee commented
Tested on Fedora 36, Nvidia GTX1080, X11 session. The extension is working.

With Clapper Sink,
![Screenshot from 2022-09-18 03-47-20](https://user-images.githubusercontent.com/25530920/190872365-f1cefa30-6e11-40e4-bf99-1b79c3790d6b.png)

With MediaFile (fallback),
![Screenshot from 2022-09-18 03-50-05](https://user-images.githubusercontent.com/25530920/190872366-7fce5703-2310-4c68-81c7-f17a8a15019f.png)

Huge improvement! 🔥

Note: 
* `gtk4paintablesink` is untested. It doesn't seem to be packaged in the Fedora repo. (Is there any easy way to install the plugin?)

2022-09-17 20:56 UTC, Rafostar commented
> Huge improvement!

Great it works for you.

> Revert codePath changes

Please just point out anything that you disagree with or if I have broken something by accident. I will just drop/edit my own commits before marking this draft as ready.

> gtk4paintablesink is untested. It doesn't seem to be packaged in the Fedora repo. (Is there any easy way to install the plugin?)

Install with `cargo` is easiest probably. Its uploaded on crates.io: [https://crates.io/crates/gst-plugin-gtk4/](https://crates.io/crates/gst-plugin-gtk4/). There are also instructions how to build manually on gstreamer gitlab readme: [https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs#building](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs#building). I added it as a "bonus", as I thought that more people might have/be willing to install official sink made by gstreamer devs instead of mine own 3rd party work. Currently Clapper sink should be still far ahead both performance and feature wise compared to that one if that is what you are asking.

2022-09-18 03:24 UTC, jeffshee commented
> Please just point out anything that you disagree with or if I have broken something by accident.

Got it! 👌

I also built the `gtk4paintablesink` and tested the `renderer.js`. The performance though was just about the same with the MediaFile. I'm not sure if there is some misconfiguration leading to poor performance or if it's just its current limitation.

![Screenshot from 2022-09-18 11-54-20](https://user-images.githubusercontent.com/25530920/190883682-86aea00b-c83b-4edc-8550-e5780066a52b.png)

Pipeline dot file:
[pipeline-gtk4paintablesink.zip](https://github.com/jeffshee/gnome-ext-hanabi/files/9592984/pipeline-gtk4paintablesink.zip)

2022-09-18 07:04 UTC, Rafostar commented
> I'm not sure if there is some misconfiguration leading to poor performance or if it's just its current limitation.

In case of "gtk4paintablesink" its current limitation. As I said earlier above: "Currently Clapper sink should be still far ahead both performance and feature wise compared to that one if that is what you are asking."

I just made your code work with fallback, assuming its better for your app to work with worse performance on systems without clapper installed then to not work at all. Maybe one day it will catch up. All that said, as for Clapper itself, if there was an official sink that worked when I started making Clapper player, I would just use it myself instead of making my own one.

2022-09-18 08:16 UTC, jeffshee commented
>In case of "gtk4paintablesink" its current limitation.

I see. If so then I have no problem with the current fallback implementation: Clapper > gtk4paintablesink > MediaFile, it seems reasonable.

>It is possible to enable and use VA plugin from within the code (not part of this MR). Since VA is new and still considered experimental I did not do it here.

I agree with you on this too. It's a good idea to avoid experimental plugins by default.

2022-09-18 11:25 UTC, Rafostar commented
@jeffshee 
I updated the MR with dropping the `codePath` changes as requested. Please check if everything is OK. Marking it as ready then. You might also want to later mention about this optional Clapper sink usage in readme for users to be aware.

> It's a good idea to avoid experimental plugins by default.

Yes, but you might consider to either mention this VA plugin or maybe add a command line arg that enables it? You (Nvidia user) seem to be fine here, but Intel/AMD Wayland session users might prefer using experimental options if it improves performance and battery life for them.

2022-09-21 15:01 UTC, merged